### ISSUE TITLE
Prevent mandatory fields explicitly set to `null` from throwing an exception

### ISSUE THREAD

**Issue by jonas-grgt** [jonas-grgt/bob#12]
Prevent mandatory fields **explicitly** set to `null` from throwing a `MandatoryFieldMissingException`.

Given the following class:
```java
class Car {
    public Car(String make) {
```

When used in such a way:
```java
new CarBuilder().make(null).build();
```

Should not throw an exception because it is explicitly set to the value `null`.

Introduce a new `ConstructorPolicy`

```java
/**
* Requires all fields
* to be explicitly set with a concrete value or {@code null} in the constructor.
* If any field is not set, the builder will throw an exception.
* The main difference with {@link ConstructorPolicy#ENFORCED} is that fields are considered
* to be set to, even if set explicitly to {@code null}
*/
ENFORCED_ALLOW_NULLS,
```

Possible solution is by expanding `RequiredField` by adding a field that tracks if the `fieldValue` has been set or not.

**Comment by JoranVanBelle** [comment]
I would add an extra Boolean field keeping track whether it is set or not and putting it in front of the null check
