### ISSUE TITLE
Pick up setters as buildable

### ISSUE THREAD

**Issue by jonas-grgt** [jonas-grgt/bob#2]
```

@Buildable
class Person {
  private int age;
  private String name;

  Person(int age) {
    this.age = age
  }

  void setName(String name) {
    this.name = name
  }
}

```

Allow Bob to pickup fields only accessible through explicit setters.

**Comment by donalmurtagh** [comment]
In practice, the class, constructor, and setter are more likely to have public scope rather than default scope. I omitted "public" in my tweet because of the character limit.

**Comment by nvtuanqti212** [comment]
How can i research on this problem sir. 
I am a newbie java dev, i found difficult reading this source code. Do you have any contact that we can exchange the information please sir

**Comment by jonas-grgt** [comment]
Hi @nvtuanqti212 I, unfortunately, just started working on this issue but if you want to help out there are other things that can be done. No issues created yet, though. I sent you an invite through Linkedin.

**Comment by nvtuanqti212** [comment]
i have connected to you through Linkedin sir, please check it

**Comment by jonas-grgt** [comment]
@donalmurtagh this will be possible as for release 0.2.0, thanks!
