### ISSUE TITLE
Solve warning when compiling with newer java versions 

### ISSUE THREAD

**Issue by jonas-grgt** [jonas-grgt/bob#24]
```
[WARNING] Supported source version 'RELEASE_8' from annotation processor 'io.jonasg.bob.BuildableProcessor' less than -source '21'
```

More information on how to properly deal with this can be found here: https://stackoverflow.com/questions/8185331/forward-compatible-java-6-annotation-processor-and-supportedsourceversion

**Comment by JoranVanBelle** [comment]
I will take a look at it
