### ISSUE TITLE
Update CI Java matrix to take all java version into account starting from 8

### ISSUE THREAD

**Issue by jonas-grgt** [jonas-grgt/bob#26]

**Comment by JoranVanBelle** [comment]
I will look into this. Do you only want to check the LTS versions or also version 9 etc?
Also I think [spotless stopped supporting java 8](https://github.com/diffplug/spotless/issues/1337) as of january 2023. 
What is the preference? An older spotless version that cannot be upgraded or skip java 8 in the matrix
